secure.http_mods = learning_core
secure.enable_security = true
secure.trusted_mods = learning_core

# LearnFirstEngine API
llu_backend_url = http://directus:8055
llu_api_token = V5VLAUIgTwcEavjXUKLC1vTFt1hHAugI